### ISSUE TITLE
`growthcleanr` has been archived from CRAN

### ISSUE THREAD

**Issue by mcanouil** [mcanouil/eggla#124]
https://cran.r-project.org/package=growthcleanr

`eggla` should rely on the GitHub repository?

**Comment by mcanouil** [comment]
It might get back on CRAN:
- https://github.com/carriedaymont/growthcleanr/pull/141

**Comment by burrowsk** [comment]
That's encouraging, lets see if it does appear back on Cran, otherwise we will have to rely on GitHub repo.


------------------------------------------------------------------



Dr. Kimberley Burrows

Senior Research Associate in Epidemiology
Centre for Academic Child Health

Bristol Medical School

University of Bristol



Email: ***@***.******@***.***>

http://www.bristol.ac.uk/medical-school/

Profile-Kimberley-Burrows<https://research-information.bris.ac.uk/en/persons/kimberley-burrows(2513bf22-07b2-44e9-ad72-133c3be48c17).html>



Top 10 UK university and 61st in the world (QS Rankings 2023)
Top 5 UK university for research (THE analysis of REF 2021)
4th most targeted university by top UK employers (High Fliers 2023)


My pronouns are she/her



________________________________
